apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "movietime-bff.fullname" . }}
  labels:
    {{- include "movietime-bff.labels" . | nindent 4 }}

data:
  DB_HOST: {{ .Values.moviedatabase.fullnameOverride | quote }}
  DB_PORT: {{ .Values.moviedatabase.service.ports.postgresql | quote }}
  DB_NAME: {{ .Values.moviedatabase.auth.database | quote }}
  DB_USERNAME: {{ .Values.moviedatabase.auth.username | quote }}
