apiVersion: v1
kind: Secret
metadata:
  name: {{ include "movietime-bff.fullname" . }}
  labels:
    {{- include "movietime-bff.labels" . | nindent 4 }}

type: Opaque

data:
  MOVIE_DB_API_KEY: {{ .Values.config.movieDbService.apiKey | b64enc | quote }}

  DB_PASSWORD: {{ .Values.moviedatabase.auth.password | b64enc | quote }}
